name: test-suite
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  nix-tests:
    name: Run nix tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Check Nix Flake
        run: |
          nix flake check

  cross-platform-tests:
    name: Run tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13
        with:
          cli: latest

      - name: Clojure tests
        shell: bash
        run: |
          cd clj
          export PATH=../rust/target/debug:$PATH
          clojure -X:test

      - name: Check Clojure pom.xml
        if: matrix.os == 'ubuntu-latest'
        run: |
          cd clj
          clojure -T:build write-pom
          git diff --exit-code pom.xml


  check-jarfiles:
    name: Check jarfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@13
        with:
          cli: latest

      - name: Build and install jarfile locally
        run: |
          cd clj
          clojure -T:build install

      - name: Print version from jarfile
        run: |
          VERSION=$(grep '^version' rust/limabean/Cargo.toml | head -1 | cut -d'"' -f2)
          # this must run *outside* of the clj directory, so we're not relying on its deps.edn for dependency resolution
          clojure -J--enable-native-access=ALL-UNNAMED -Sdeps "{:mvn/local-repo \"$(pwd)/target/m2\" :deps {io.github.tesujimath/limabean {:mvn/version \"$VERSION\"}}}" -M -m limabean.main --version >VERSION
          cat VERSION
          test "$(cat VERSION)" == "limabean.clj $VERSION"

      - name: Build uberjar
        run: |
          cd clj
          clojure -T:build uber

      - name: Print version from uberjar
        run: |
          VERSION=$(grep '^version' rust/limabean/Cargo.toml | head -1 | cut -d'"' -f2)
          java -jar ./clj/target/limabean-${VERSION}-standalone.jar --version >VERSION
          cat VERSION
          test "$(cat VERSION)" == "limabean.clj $VERSION"
